[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput --settings=jobs.settings.production"

[deploy]
startCommand = "gunicorn jobs.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2 --timeout 60"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[service]
internal_port = 8000 