# Generated by Django 5.1.2 on 2025-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('employee', 'Employee')], error_messages={'required': 'Role must be provided'}, max_length=12),
        ),
    ]
