# Generated by Django 5.1.2 on 2025-01-29 10:51

import django.db.models.deletion
import jobsapp.models
from django.db import migrations, models
import json


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0019_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunSQL(
            # Forward SQL: Copy data from category to category_temp and set category to NULL
            "UPDATE jobsapp_job SET category_temp = category, category = NULL;",
            # Reverse SQL: Copy data back from category_temp to category
            "UPDATE jobsapp_job SET category = category_temp;"
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='importerror',
            name='raw_values',
            field=models.JSONField(encoder=json.JSONEncoder),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsapp.category'),
        ),
    ]
