# Generated by Django 5.1.2 on 2025-01-29 10:51

from django.db import migrations
from django.utils.text import slugify

def create_categories_and_update_jobs(apps, schema_editor):
    Category = apps.get_model('jobsapp', 'Category')
    Job = apps.get_model('jobsapp', 'Job')
    
    # Define the initial categories
    categories = [
        'Web Design',
        'Graphic Design',
        'Web Development',
        'Human Resources',
        'Support',
        'Android Development'
    ]
    
    # Create categories
    category_mapping = {}
    for cat_name in categories:
        slug = slugify(cat_name)
        category = Category.objects.create(
            name=cat_name,
            slug=slug
        )
        category_mapping[slug] = category
    
    # Update existing jobs
    for job in Job.objects.all():
        if job.category_temp:
            # Try to find matching category
            matching_category = category_mapping.get(job.category_temp)
            if matching_category:
                job.category = matching_category
                job.save()

def reverse_migrate(apps, schema_editor):
    Category = apps.get_model('jobsapp', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0020_category_alter_importerror_raw_values_and_more'),
    ]

    operations = [
        migrations.RunPython(create_categories_and_update_jobs, reverse_migrate),
        migrations.RemoveField(
            model_name='job',
            name='category_temp',
        ),
    ]
