# Generated by Django 5.1.2 on 2025-01-31 14:25

import jobsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0021_migrate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importerror',
            name='raw_values',
            field=models.JSONField(encoder=jobsapp.models.DecimalEncoder),
        ),
    ]
